### PR TITLE
adds Ruby-Brady.png

### PR DESCRIPTION
**Pull request by joel-g**
I couldn't decide if I should the color of Brady so it didn't match the scala one but the colors were perfect for ruby so I left it.

### CODE REVIEW

**Comment by EgoAleSum** [comment]
Hi @joel-g and thank you very much for creating this! Really appreciate your contribution.

Before I can merge that, I would need to ask you to please create a vector version of this too, in SVG format (you can look at the other Brady's as example). Also, make you could make the red a slightly different hue of red? Just so it's not the exact same color as the Scala one :) (no big deal, however).

On a side note, I've done some research and looks like the Ruby logo is released under a Creative Commons license too: https://www.ruby-lang.org/en/about/logo/ It should be ok for us to use it, but let me double-check with our legal team if there's any caveat.

Thank you again for this!

**Comment by joel-g** [comment]
@EgoAleSum I will work on an SVG tomorrow and change the colors. That's exactly where I took the logo from and came to the same conclusion.

**Comment by EgoAleSum** [comment]
Hi @joel-g Do you have any update on the design changes?

Also, I wanted to let you know that we've received written permission by the authors of Ruby to use the logo in this fashion.

**Comment by joel-g** [comment]
Sorry been busy. Here's the SVG. Spent a lot of time getting that file size down but the Ruby logo is complex. I sourced from the PDF at https://www.ruby-lang.org/en/about/logo/

**Comment by joel-g** [comment]
I did this work from home but I'm on a MSFT contract right now so let me check with my manager before I sign that

**Comment by joel-g** [comment]
@EgoAleSum this is all done

**Comment by ItalyPaleAle** [comment]
@joel-g  Sorry for the delay. Merging this. Thank you!

**Pull request merged**
